Modifed to run inside of a container
cbrownstein-lambda/lambda-docs-mkdocs pull request #14
Opened 2024-08-23 16:57 UTC by ryaeng

- Modified Dockerfile to use /docs directory and use requirements.txt
- Modified README.md to include instructions on how to run in a container

## Description
Modifies the Dockerfile so that mkdocs can be run insider of a container locally. README.md was also modified to include instructions on how to run inside of a container.

## Related issues

N/A

## Checklist

- [ x] Documentation follows the style guidelines of the project.
- [ ] Files used in this PR (e.g., images and PDFs) are committed.
- [x ] Changes have been tested locally.
- [ ] Reviewers have been assigned (at least 1 tech writer and 1 eng).

## Additional notes
Loving the new documentation. Keep up the good work!!!

2024-08-23 21:08 UTC, cbrownstein-lambda requested changes

2024-08-23 21:08 UTC, cbrownstein-lambda commented on README.md
> +    Congratulation, your local preview is now live inside of a container!
Fix indentation (this isn't part of the step) and use more common spelling.

```suggestion
Congratulations, your local preview is now live inside of a container!
```

2024-08-26 14:44 UTC, smithbrady reviewed
looks good!

2024-08-26 18:50 UTC, cbrownstein-lambda approved these changes

2024-08-26 18:51 UTC, merged