Create security-posture.md
cbrownstein-lambda/lambda-docs-mkdocs pull request #17
Opened 2024-09-19 18:45 UTC by ta11t0m

Add 1CC Security Posture to PoC docs site.

## Description

## Related issues

- [CEX-12345] (JIRA)
- #12345 (GitHub)

## Checklist

- [ ] Documentation follows the style guidelines of the project.
- [ ] Files used in this PR (e.g., images and PDFs) are committed.
- [ ] Link to existing documentation and the reverse.
- [ ] Changes have been tested locally.
- [ ] Reviewers have been assigned (at least 1 tech writer and 1 eng).

## Additional notes

2024-09-19 18:49 UTC, ta11t0m commented
![1cc-network-architecture](https://github.com/user-attachments/assets/c3987608-3573-4fbd-ba2c-912373a71025)
Forgot to add the image asset

2024-09-19 22:10 UTC, pete-lambda requested changes
Found a few nits. Have at it!

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +[JupyterLab's security documentation[(https://jupyter-server.readthedocs.io/en/latest/operators/security.html).
Malformed URL -- the closing ] is actually an opening [

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +By default, management nodes are directly accessible over the Internet via SSH and via a public
"internet" has been officially demoted to [common noun status](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/internet-intranet-extranet).

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +## Infiniband interconnect
InfiniBand should be CamelCapped.

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +only ever transits physical IB links dedicated to that customer, ensuring complete isolation of
I don't think we should be colloquial with the IB reference, since it's NVIDIA IP.

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +*   24x7x365 in-house and on-site security qualified personnel
Hyphenate "security-qualified"

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +*   24x7x365 in-house and on-site security qualified personnel
Or flip to "on-site qualified security personnel"

2024-09-19 22:10 UTC, pete-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +Authorized Lambda employees may access data centers for maintenance, upgrade, or other hardware
"upgrades" (plural)?

2024-09-23 23:55 UTC, ta11t0m commented on docs/public-cloud/1-click-clusters/security-posture.md
> +![1cc-network-architecture](../../assets/images/1cc-network-architecture.png)
Fixed.

2024-09-23 23:55 UTC, ta11t0m commented on docs/public-cloud/1-click-clusters/security-posture.md
> +[JupyterLab's security documentation[(https://jupyter-server.readthedocs.io/en/latest/operators/security.html).
Done.

2024-09-24 00:21 UTC, cbrownstein-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +![1cc-network-architecture](../../assets/images/1cc-network-architecture.png)
Fixed in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/17/commits/0decdf493e5c68e6bfc079597906317c1d01861e.

2024-09-24 00:23 UTC, cbrownstein-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +[JupyterLab's security documentation[(https://jupyter-server.readthedocs.io/en/latest/operators/security.html).
Fixed in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/17/commits/a2fbf525ca149311dd598cb00fb0052b830eac74.

2024-09-24 00:25 UTC, cbrownstein-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +## Infiniband interconnect
Fixed in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/17/commits/b2f562e832fffc59fa41bc6bd41680d373033983.

2024-09-24 00:26 UTC, cbrownstein-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +*   24x7x365 in-house and on-site security qualified personnel
@ta11t0m Thoughts about this?

2024-09-24 00:30 UTC, ta11t0m commented on docs/public-cloud/1-click-clusters/security-posture.md
> +*   24x7x365 in-house and on-site security qualified personnel
"Qualified in-house security personnel on site 24x7x365"

2024-09-24 00:39 UTC, cbrownstein-lambda commented on docs/public-cloud/1-click-clusters/security-posture.md
> +*   24x7x365 in-house and on-site security qualified personnel
```suggestion
*   Qualified in-house security personnel on site 24x7x365
```

2024-09-24 01:07 UTC, cbrownstein-lambda approved these changes
LGTM!

2024-09-24 01:29 UTC, merged