Set up redirects
cbrownstein-lambda/lambda-docs-mkdocs pull request #35
Opened 2024-10-07 20:15 UTC by cbrownstein-lambda

## Description

This PR sets up redirects for the migration.

## Related issues

None

## Checklist

- [ ] ~~Documentation follows the [contributing guidelines](../CONTRIBUTING.md).~~
- [ ] ~~Documentation linked to in nav and index pages.~~
- [ ] ~~Files used in this PR (e.g., images and PDFs) are committed.~~
- [ ] ~~Link to existing documentation and the reverse.~~
- [x] Changes have been tested locally.
- [x] Reviewers have been assigned (at least 1 tech writer and 1 eng).

## Additional notes

The redirects are believed to be but might not be 100% up to date.

2024-10-07 21:42 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/tutorial-getting-started-with-training-a-machine-learning-model.md': 'education/tutorial-getting-started-with-training-a-machine-learning-model.md'
has this been migrated?

2024-10-07 21:42 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/demos.md': 'public-cloud/on-demand/demos.md'
has this been migrated?

2024-10-07 21:43 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/deploying-llama-3.2-3b-in-a-kubernetes-k8s-cluster.md': 'education/large-language-models/deploying-llama-3.2-3b-in-a-kubernetes-k8s-cluster.md'
not yet migrated

2024-10-07 21:45 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/how-to-serve-the-llama-3.1-8b-and-70b-models-using-lambda-cloud-on-demand-instances.md': 'education/large-language-models/how-to-serve-the-llama-3.1-8b-and-70b-models-using-l
```suggestion
        'on-demand-cloud/how-to-serve-the-llama-3.1-8b-and-70b-models-using-lambda-cloud-on-demand-instances.md': 'education/large-language-models/serving-llama-3-1-docker.md'
```

2024-10-07 21:46 UTC, ryanlambda commented on mkdocs.yml
> +        'software/using-the-lambda-bug-report-to-troubleshoot-your-system.md': 'education/linux-usage/using-the-lambda-bug-report-to-troubleshoot-your-system.md'
not migrated afaict

2024-10-07 21:46 UTC, ryanlambda commented on mkdocs.yml
> +        'software/using-the-nvidia-bug-report.log-file-to-troubleshoot-your-system.md': 'education/linux-usage/using-the-nvidia-bug-report.log-file-to-troubleshoot-your-system.md'
not migrated afaict

2024-10-07 21:47 UTC, ryanlambda commented on mkdocs.yml
> +        'software/troubleshooting-and-debugging.md': 'education/linux-usage/troubleshooting-and-debugging.md'
not migrated yet

2024-10-07 21:47 UTC, ryanlambda commented on mkdocs.yml
> +        'software/lambda-stack-and-recovery-images.md': 'education/linux-usage/lambda-stack-and-recovery-images.md'
not migrated yet

2024-10-07 21:47 UTC, ryanlambda commented on mkdocs.yml
> +        'software/configuring-software-raid.md': 'education/linux-usage/configuring-software-raid.md'
not yet migrated

2024-10-07 21:49 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/team.md': 'public-cloud/team.md'
```suggestion
        'on-demand-cloud/team.md': 'public-cloud/teams.md'
```

2024-10-07 21:50 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/overview.md': 'public-cloud/on-demand/overview.md'
```suggestion
        'on-demand-cloud/overview.md': 'public-cloud/on-demand/index.md'
```

2024-10-07 21:51 UTC, ryanlambda commented on mkdocs.yml
> +        'tensorbook/getting-started.md': 'hardware/tensorbook/getting-started.md'
not migrated yet

2024-10-07 21:51 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/file-systems.md': 'public-cloud/file-systems.md'
```suggestion
        'on-demand-cloud/file-systems.md': 'public-cloud/filesystems.md'
```

2024-10-07 21:52 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/firewall.md': 'public-cloud/firewall.md'
```suggestion
        'on-demand-cloud/firewall.md': 'public-cloud/firewalls.md'
```

2024-10-07 21:53 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/deploying-a-llama-3-inference-endpoint.md': 'education/large-language-models/deploying-a-llama-3-inference-endpoint.md'
not yet migrated

2024-10-07 21:54 UTC, ryanlambda commented on mkdocs.yml
> +        'on-demand-cloud/deploying-models-with-dstack.md': 'education/scheduling-and-orchestration/deploying-models-with-dstack.md'
```suggestion
        'on-demand-cloud/deploying-models-with-dstack.md': 'education/scheduling-and-orchestration/dstack-vllm-llama-3-1.md'
```

2024-10-07 21:55 UTC, ryanlambda commented on mkdocs.yml
> +        'software/basic-linux-commands-and-system-administration.md': 'education/linux-usage/basic-linux-commands-and-system-administration.md'
not yet migrated

2024-10-07 21:57 UTC, ryanlambda commented on mkdocs.yml
> +        '1-click-clusters/serving-llama-3.1-405b-on-a-lambda-1-click-cluster.md': 'education/large-language-models/serving-llama-3-1-405b.md'
currently this file is called "serving-llama-3_1-405b.md", but i support changing the underscore to a hyphen

2024-10-07 21:57 UTC, ryanlambda commented on mkdocs.yml
> +        'servers/getting-started.md': 'hardware/servers/getting-started.md'
not yet migrated

2024-10-07 22:00 UTC, ryanlambda commented on mkdocs.yml
> +        'software/virtual-environments-and-docker-containers.md': 'education/programming/virtual-environments-containers.md'
```suggestion
        'software/virtual-environments-and-docker-containers.md': 'education/linux-usage/virtual-environments-containers.md'
```

2024-10-07 22:05 UTC, ryanlambda requested changes
We'll need to migrate most of these before I can verify the redirects.
Also: added some suggestions to resolve a few issues with path and name changes.

2024-10-07 22:31 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'on-demand-cloud/team.md': 'public-cloud/team.md'
"Team" is (was?) considered a feature rather than a common noun. Thoughts?

2024-10-08 23:31 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'on-demand-cloud/demos.md': 'public-cloud/on-demand/demos.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:32 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'on-demand-cloud/deploying-llama-3.2-3b-in-a-kubernetes-k8s-cluster.md': 'education/large-language-models/deploying-llama-3.2-3b-in-a-kubernetes-k8s-cluster.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:33 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/using-the-lambda-bug-report-to-troubleshoot-your-system.md': 'education/linux-usage/using-the-lambda-bug-report-to-troubleshoot-your-system.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:33 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/using-the-nvidia-bug-report.log-file-to-troubleshoot-your-system.md': 'education/linux-usage/using-the-nvidia-bug-report.log-file-to-troubleshoot-your-system.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:34 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/troubleshooting-and-debugging.md': 'education/linux-usage/troubleshooting-and-debugging.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:34 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/lambda-stack-and-recovery-images.md': 'education/linux-usage/lambda-stack-and-recovery-images.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:34 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/configuring-software-raid.md': 'education/linux-usage/configuring-software-raid.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:34 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'tensorbook/getting-started.md': 'hardware/tensorbook/getting-started.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:34 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'on-demand-cloud/deploying-a-llama-3-inference-endpoint.md': 'education/large-language-models/deploying-a-llama-3-inference-endpoint.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:35 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'software/basic-linux-commands-and-system-administration.md': 'education/linux-usage/basic-linux-commands-and-system-administration.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-08 23:36 UTC, cbrownstein-lambda commented on mkdocs.yml
> +        'servers/getting-started.md': 'hardware/servers/getting-started.md'
Pages migrated in https://github.com/cbrownstein-lambda/lambda-docs-mkdocs/pull/35/commits/f9df135e440a0fb5237cdc624f3418abb2f5301b.

2024-10-10 00:23 UTC, ta11t0m commented on mkdocs.yml
>          'one-click-clusters/getting-started.md': 'public-cloud/1-click-clusters/getting-started.md'
the destination path will need to change to /index.md once #40 is submitted.

2024-10-14 20:28 UTC, cbrownstein-lambda commented on docs/education/large-language-models/deploying-a-llama-3-inference-endpoint.md
> +   * Model 70B ([meta-llama/Meta-Llama-3-70B)](https://huggingface.co/meta-llama/Meta-Llama-3-70B) requires 8x A100 or H100 GPU nodes.
```suggestion
    * Model 8B ([meta-llama/Meta-Llama-3-8B)](https://huggingface.co/meta-llama/Meta-Llama-3-8B) requires 1x A100 or H100 GPU node.
    * Model 70B ([meta-llama/Meta-Llama-3-70B)](https://huggingface.co/meta-llama/Meta-Llama-3-70B) requires 8x A100 or H100 GPU nodes.
```

2024-10-14 20:28 UTC, cbrownstein-lambda commented on docs/education/large-language-models/deploying-a-llama-3-inference-endpoint.md
> +    ==="Llama3 70B"
```suggestion
    === "Llama3 70B"
```

2024-10-16 20:54 UTC, ryanlambda commented on docs/public-cloud/firewalls.md
Nit: I'd argue this is better placed before the steps. If you place it after the steps, the user might already have made the mistake it's warning about.

2024-10-16 21:56 UTC, ryanlambda commented on docs/education/programming/virtual-environments-containers.md
> +  - Virtualization
```suggestion
  - virtualization
```

Rationale: Consistency. All of the other tags are lower-case.

2024-10-16 22:24 UTC, ryanlambda approved these changes
A few minor nits. I saw some other more major issues, but the current state of things makes it hard to tell if they're already going to be solved in subsequent PRs. I'm just going to assume they are and approve for now, and we can do a QA check after the dust has settled.

2024-10-16 22:58 UTC, ta11t0m approved these changes

2024-10-16 23:05 UTC, merged